config/routes.rb
Calc::Application.routes.draw do
  
  resources :budgets do
    member do
      get 'summarize'
    end
    resource :general_settings, :hardware_prices, :lan_settings, :settings
    resources :workstations_settings, :furnishings, :software
  end

  
  match 'welcome/about' => 'welcome#index', :as => :about
  root :to => 'welcome#about'
  

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  
  has_one :general_settings, :dependent => :delete
  has_one :hardware_prices, :dependent => :delete
  has_one :lan_settings, :dependent => :delete
  
  has_many :workstations_settings, 
           :class_name => 'WorkstationsSettings',
           :dependent => :delete_all
  has_one :students_workstations_settings,
          :class_name => 'WorkstationsSettings',
          :conditions => ['target = ?', WorkstationsSettings::Target::STUDENTS]
  has_one :teachers_workstations_settings,
          :class_name => 'WorkstationsSettings',
          :conditions => ['target = ?', WorkstationsSettings::Target::TEACHERS]
  has_one :servers_workstations_settings,
          :class_name => 'WorkstationsSettings',
          :conditions => ['target = ?', WorkstationsSettings::Target::SERVERS]
  has_one :thin_clients_workstations_settings,
          :class_name => 'WorkstationsSettings',
          :conditions => ['target = ?', WorkstationsSettings::Target::THIN_CLIENTS]

  has_many :furnishings,
           :class_name => 'Furnishings',
           :dependent => :delete_all
  has_one :students_furnishings,
          :class_name => 'Furnishings',
          :conditions => ['target = ?', Furnishings::Target::STUDENTS]
  has_one :teachers_furnishings,
          :class_name => 'Furnishings',
          :conditions => ['target = ?', Furnishings::Target::TEACHERS]
  has_one :servers_furnishings,
          :class_name => 'Furnishings',
          :conditions => ['target = ?', Furnishings::Target::SERVERS]
          
  has_many :software,
           :class_name => 'Software',
           :dependent => :delete_all
  has_one :students_standalone_software,
          :class_name => 'Software',
          :conditions => ['target = ?', Software::Target::STUDENTS_STANDALONE]
  has_one :teachers_standalone_software,
          :class_name => 'Software',
          :conditions => ['target = ?', Software::Target::TEACHERS_STANDALONE]
  has_one :tc_server_software,
          :class_name => 'Software',
          :conditions => ['target = ?', Software::Target::TC_SERVER]
  has_one :tc_software,
          :class_name => 'Software',
          :conditions => ['target = ?', Software::Target::TC]

  has_one :settings, :dependent => :delete

  cattr_reader :per_page
  @@per_page = 5
  
  validates_presence_of :name
  validates_length_of :name, :within => 3..255, :allow_blank => true
  validates_uniqueness_of :name, :allow_blank => true
  
  validates_length_of :description, :minimum => 3, :allow_blank => true
  
  before_save :downcase_attrs
    
  private
  
  def downcase_attrs
    name.downcase! if name
    description.downcase! if description
  end
  
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  
  prawnto :inline => false
  
  def index
    @budgets = Budget.paginate :page => params[:page]
  end
  
  def new
    @budget = Budget.new
  end
  
  def create
    @budget = Budget.new params[:budget]
    
    if @budget.save
      flash[:notice] = "#{Budget.model_name.human.humanize} #{t 'msgs.saved'}"
      redirect_to @budget
    else
      render :action => 'new'
    end
  end
  
  def show
    @budget = Budget.find_by_id params[:id], 
                                :include => [:general_settings, :hardware_prices, 
                                            :lan_settings, :students_workstations_settings, 
                                            :teachers_workstations_settings, 
                                            :servers_workstations_settings, 
                                            :thin_clients_workstations_settings, 
                                            :students_furnishings, :teachers_furnishings, 
                                            :servers_furnishings, :students_standalone_software, 
                                            :teachers_standalone_software, :tc_server_software, 
                                            :tc_software, :settings]
    
    unless @budget
      flash[:error] = "#{Budget.model_name.human.humanize} #{t 'msgs.record_not_found'}"
      redirect_to budgets_path
    end
  end
  
  def summarize
    @budget = Budget.find_by_id params[:id], 
                                :include => [:general_settings, :hardware_prices, 
                                            :lan_settings, :students_workstations_settings, 
                                            :teachers_workstations_settings, 
                                            :servers_workstations_settings, 
                                            :thin_clients_workstations_settings, 
                                            :students_furnishings, :teachers_furnishings, 
                                            :servers_furnishings, :students_standalone_software, 
                                            :teachers_standalone_software, :tc_server_software, 
                                            :tc_software, :settings]
    
    unless @budget
      flash[:error] = "#{Budget.model_name.human.humanize} #{t 'msgs.record_not_found'}"
      redirect_to budgets_path
    end
  end
  
  def edit
    @budget = Budget.find_by_id params[:id]
    
    unless @budget
      flash[:error] = "#{Budget.model_name.human.humanize} #{t 'msgs.record_not_found'}"
      redirect_to budgets_path
    end
  end
  
  def update
    @budget = Budget.find params[:id]
    
    if @budget.update_attributes params[:budget]
      flash[:notice] = "#{Budget.model_name.human.humanize} #{t 'msgs.saved'}"
      redirect_to @budget
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @budget = Budget.find params[:id]
    @budget.destroy
    flash[:notice] = "#{Budget.model_name.human.humanize} #{t 'msgs.deleted'}"
    redirect_to budgets_path
  end
  
end

app/helpers/budgets_helper.rb
module BudgetsHelper
  
  def to_table budget
    # ITEM, DESCRIPTION, UNIT PRICE, QUANTITY, SUBTOTAL.
    items = []
    if budget.settings.students_standalone_workstations_enabled &&
        budget.settings.students_standalone_workstations_cost > 0
      item = Settings.human_attribute_name 'students_standalone_workstations_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.students_workstations_settings.total_cost), 
                budget.general_settings.students_workstations_count,
                number_to_currency(budget.settings.students_standalone_workstations_cost)]
    end
    
    if budget.settings.teachers_standalone_workstations_enabled &&
        budget.settings.teachers_standalone_workstations_cost > 0
      item = Settings.human_attribute_name 'teachers_standalone_workstations_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.teachers_workstations_settings.total_cost), 
                budget.general_settings.teachers_count,
                number_to_currency(budget.settings.teachers_standalone_workstations_cost)]
    end
    
    if budget.settings.thin_clients_enabled &&
        budget.settings.thin_clients_cost > 0
      item = Settings.human_attribute_name 'thin_clients_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.thin_clients_workstations_settings.total_cost), 
                budget.general_settings.students_workstations_count,
                number_to_currency(budget.settings.thin_clients_cost)]
    end
    
    if budget.settings.thin_clients_server_enabled &&
        budget.settings.thin_clients_server_cost > 0
      item = Settings.human_attribute_name 'thin_clients_server_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.servers_workstations_settings.total_cost), 
                budget.general_settings.servers_count,
                number_to_currency(budget.settings.thin_clients_server_cost)]
    end
    
    if budget.settings.lan_enabled &&
        budget.settings.lan_cost > 0
      item = Settings.human_attribute_name 'lan_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.lan_settings.total_cost), 
                1,
                number_to_currency(budget.lan_settings.total_cost)]
    end
    
    if budget.settings.printers_count > 0 &&
        budget.settings.printers_cost > 0
      items << [t('msgs.printers').humanize, 
                '...', 
                nbr_to_curr(budget.hardware_prices, :printer_unit_price), 
                budget.settings.printers_count,
                number_to_currency(budget.settings.printers_cost)]
    end
    
    if budget.settings.scanners_count > 0 &&
        budget.settings.scanners_cost > 0
      items << [t('msgs.scanners').humanize, 
                '...', 
                nbr_to_curr(budget.hardware_prices, :scanner_unit_price), 
                budget.settings.scanners_count,
                number_to_currency(budget.settings.scanners_cost)]
    end
    
    if budget.settings.students_furnishings_enabled &&
        budget.settings.students_furnishings_cost > 0
      item = Settings.human_attribute_name 'students_furnishings_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.students_furnishings.total_cost), 
                budget.general_settings.students_workstations_count,
                number_to_currency(budget.settings.students_furnishings_cost)]
    end
    
    if budget.settings.teachers_furnishings_enabled &&
        budget.settings.teachers_furnishings_cost > 0
      item = Settings.human_attribute_name 'teachers_furnishings_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.teachers_furnishings.total_cost), 
                budget.general_settings.teachers_count,
                number_to_currency(budget.settings.teachers_furnishings_cost)]
    end
    
    if budget.settings.servers_furnishings_enabled &&
        budget.settings.servers_furnishings_cost > 0
      item = Settings.human_attribute_name 'servers_furnishings_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.servers_furnishings.total_cost), 
                budget.general_settings.servers_count,
                number_to_currency(budget.settings.servers_furnishings_cost)]
    end
    
    if budget.settings.prop_students_soft_enabled? &&
        budget.settings.students_software_cost > 0
      item = Settings.human_attribute_name 'prop_students_soft_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.students_standalone_software.total_cost), 
                budget.general_settings.students_workstations_count,
                number_to_currency(budget.settings.students_software_cost)]
    end
    
    if budget.settings.prop_teachers_soft_enabled? &&
        budget.settings.teachers_software_cost > 0
      item = Settings.human_attribute_name 'prop_teachers_soft_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.teachers_standalone_software.total_cost), 
                budget.general_settings.teachers_count,
                number_to_currency(budget.settings.teachers_software_cost)]
    end
    
    if budget.settings.prop_tc_soft_enabled? &&
        budget.settings.tc_software_cost > 0
      item = Settings.human_attribute_name 'prop_tc_soft_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.tc_software.total_cost), 
                budget.general_settings.students_workstations_count,
                number_to_currency(budget.settings.tc_software_cost)]
    end
    
    if budget.settings.prop_tc_server_soft_enabled? &&
        budget.settings.tc_server_software_cost > 0
      item = Settings.human_attribute_name 'prop_tc_server_soft_enabled'
      item = item[0, item.rindex(' ')].humanize
      
      items << [item, 
                '...', 
                number_to_currency(budget.tc_server_software.total_cost), 
                budget.general_settings.servers_count,
                number_to_currency(budget.settings.tc_server_software_cost)]
    end
    
    if budget.settings.building_improvements_cost > 0
      items << [Settings.human_attribute_name('building_improvements_cost').humanize, 
                '...', 
                number_to_currency(budget.settings.building_improvements_cost), 
                1,
                number_to_currency(budget.settings.building_improvements_cost)]
    end
    
    if budget.settings.electric_installation_cost > 0
      items << [Settings.human_attribute_name('electric_installation_cost').humanize, 
                '...', 
                number_to_currency(budget.settings.electric_installation_cost), 
                1,
                number_to_currency(budget.settings.electric_installation_cost)]
    end
    
    items
  end
  
end

app/views/budgets/_form.html.erb
<% unless @budget.errors.empty? %>
  <div class="error">
	  <%= error_messages_for :budget, :header_message => nil %>
  </div>
<% end %>

<%= form_for @budget do |f| %>
  <p>
    <%= f.label :name, Budget.human_attribute_name('name').humanize %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description, Budget.human_attribute_name('description').humanize %><br>
    <%= f.text_area :description, :rows => 4, :cols => 35 %>
  </p>
  <p>
    <%= f.submit t('msgs.save') %>
  </p>
<% end %>

app/views/budgets/_sidenav.html.erb
<h1><%= t 'msgs.actions' %></h1>
<ul>
	<li><%= link_to t('msgs.new'), new_budget_path %></li>
	
	<% if controller.action_name == 'show' %>
    <li><%= link_to t('msgs.pdf_version'), 
											budget_path(@budget, :format => 'pdf') %></li>
		<li><%= link_to t('msgs.edit'), edit_budget_path(@budget) %></li>
		<li><%= link_to t('msgs.delete'), @budget, :method => :delete, 
                    :confirm => t('msgs.confirmation') %></li>
		<li><%= link_to t('msgs.access_summary'), 
										summarize_budget_path(@budget) %></li>								
	<% end %>
	
	<% unless request.path == root_path %>
	 <li><%= link_to t('msgs.back'), :back %></li>
	<% end %>
</ul>

app/views/budgets/edit.html.erb
<%= content_for :page_title, "#{t 'msgs.new'} #{Budget.model_name.human}" %>
<% content_for :sidenav, render(:partial => 'sidenav') %>

<%= render :partial => 'form' %>

app/views/budgets/index.html.erb
<%= content_for :page_title, Budget.model_name.human.pluralize.humanize %>
<% content_for :sidenav, render(:partial => 'sidenav') %>

<ul>
	<% if @budgets.empty? %>
		<%= model_not_found Budget %>
	<% else %>
    <% @budgets.each do |budget| %>
		  <li>
		  	<%= link_to h(budget.name).humanize, budget %>
		  </li>
		<% end %>
	<% end %>
</ul>

<%= will_paginate @budgets %>

app/views/budgets/new.html.erb
<%= content_for :page_title, "#{t 'msgs.new'} #{Budget.model_name.human}" %>
<% content_for :sidenav, render(:partial => 'sidenav') %>

<%= render :partial => 'form' %>

app/views/budgets/show.html.erb
<%= content_for :page_title, h(@budget.name).humanize %>
<% content_for :sidenav, render(:partial => 'sidenav') %>

<% if @budget.description %>
  <p>
  	<label><%= Budget.human_attribute_name('description').humanize %></label><br>
    <%= h @budget.description.humanize  %>
  </p>
<% end %>

<p>
  <label><%= Budget.human_attribute_name('created_at').humanize %></label><br>
  <%= l @budget.created_at  %>
</p>

<p>
  <label><%= Budget.human_attribute_name('updated_at').humanize %></label><br>
  <%= l @budget.updated_at  %>
</p>

<p>
  <ul>
    <li>
      <% if @budget.general_settings %>
        <%= link_to GeneralSettings.model_name.human.humanize,
                    budget_general_settings_path(@budget) %>
      <% else %>
        <%= link_to GeneralSettings.model_name.human.humanize,
                    new_budget_general_settings_path(@budget) %>
      <% end %>
    </li>

    <li>
      <% if @budget.hardware_prices %>
        <%= link_to HardwarePrices.model_name.human.humanize,
                    budget_hardware_prices_path(@budget) %>
      <% else %>
        <%= link_to HardwarePrices.model_name.human.humanize,
                    new_budget_hardware_prices_path(@budget) %>
      <% end %>
    </li>

    <li>
      <% if @budget.lan_settings %>
        <%= link_to LanSettings.model_name.human.humanize,
                    budget_lan_settings_path(@budget) %>
      <% else %>
        <%= link_to LanSettings.model_name.human.humanize,
                    new_budget_lan_settings_path(@budget) %>
      <% end %>
    </li>

		<br/>
    <li>
      <%= t('msgs.workstations').humanize %><br/>
    	<small>
				<ul>
				  <li>
				    <% if @budget.students_workstations_settings %>
				      <%= link_to t('msgs.students').humanize,
				                  budget_workstations_settings_path(@budget, @budget.students_workstations_settings) %>
				    <% else %>
				      <%= link_to t('msgs.students').humanize,
				                  new_budget_workstations_settings_path(@budget,
				                                                        :target => WorkstationsSettings::Target::STUDENTS) %>
				    <% end %>
				  </li>
				
				  <li>
				    <% if @budget.teachers_workstations_settings %>
				      <%= link_to t('msgs.teachers').humanize,
				                  budget_workstations_settings_path(@budget, @budget.teachers_workstations_settings) %>
				    <% else %>
				      <%= link_to t('msgs.teachers').humanize,
				                  new_budget_workstations_settings_path(@budget,
				                                                        :target => WorkstationsSettings::Target::TEACHERS) %>
				    <% end %>
				  </li>
				
				  <li>
				    <% if @budget.servers_workstations_settings %>
				      <%= link_to t('msgs.servers').humanize,
				                  budget_workstations_settings_path(@budget, @budget.servers_workstations_settings) %>
				    <% else %>
				      <%= link_to t('msgs.servers').humanize,
				                  new_budget_workstations_settings_path(@budget,
				                                                        :target => WorkstationsSettings::Target::SERVERS) %>
				    <% end %>
				  </li>
				
				  <li>
				    <% if @budget.thin_clients_workstations_settings %>
				      <%= link_to t('msgs.thin_clients').humanize,
				                  budget_workstations_settings_path(@budget, @budget.thin_clients_workstations_settings) %>
				    <% else %>
				      <%= link_to t('msgs.thin_clients').humanize,
				                  new_budget_workstations_settings_path(@budget,
				                                                        :target => WorkstationsSettings::Target::THIN_CLIENTS) %>
				    <% end %>
				  </li>
				</ul>
  		</small>
    </li>

    <br/>
		<li>
      <%= t('msgs.furnishings').humanize %><br/>
			<small>
				<ul>
				  <li>
				    <% if @budget.students_furnishings %>
				      <%= link_to t('msgs.students').humanize,
				                  budget_furnishings_path(@budget, @budget.students_furnishings) %>
				    <% else %>
				      <%= link_to t('msgs.students').humanize,
				                  new_budget_furnishings_path(@budget,
				                                              :target => Furnishings::Target::STUDENTS) %>
				    <% end %>
				  </li>
				
				  <li>
				    <% if @budget.teachers_furnishings %>
				      <%= link_to t('msgs.teachers').humanize,
				                  budget_furnishings_path(@budget, @budget.teachers_furnishings) %>
				    <% else %>
				      <%= link_to t('msgs.teachers').humanize,
				                  new_budget_furnishings_path(@budget,
				                                              :target => Furnishings::Target::TEACHERS) %>
				    <% end %>
				  </li>
				
				  <li>
				    <% if @budget.servers_furnishings %>
				      <%= link_to t('msgs.servers').humanize,
				                  budget_furnishings_path(@budget, @budget.servers_furnishings) %>
				    <% else %>
				      <%= link_to t('msgs.servers').humanize,
				                  new_budget_furnishings_path(@budget,
				                                              :target => Furnishings::Target::SERVERS) %>
				    <% end %>
				  </li>
				</ul>
			</small>
    </li>
		
		<br/>
		<li>
      <%= t('msgs.software').humanize %><br/>
			<small>
				
				<ul>
				  <li>
				    <% if @budget.students_standalone_software %>
				      <%= link_to t('msgs.students').humanize,
				                  budget_software_path(@budget, @budget.students_standalone_software) %>
				    <% else %>
				      <%= link_to t('msgs.students').humanize,
				                  new_budget_software_path(@budget,
				                                          :target => Software::Target::STUDENTS_STANDALONE) %>
				    <% end %>
				  </li>
					
					<li>
				    <% if @budget.teachers_standalone_software %>
				      <%= link_to t('msgs.teachers').humanize,
				                  budget_software_path(@budget, @budget.teachers_standalone_software) %>
				    <% else %>
				      <%= link_to t('msgs.teachers').humanize,
				                  new_budget_software_path(@budget,
				                                          :target => Software::Target::TEACHERS_STANDALONE) %>
				    <% end %>
				  </li>
					
					<li>
				    <% if @budget.tc_server_software %>
				      <%= link_to t('msgs.servers').humanize,
				                  budget_software_path(@budget, @budget.tc_server_software) %>
				    <% else %>
				      <%= link_to t('msgs.servers').humanize,
				                  new_budget_software_path(@budget,
				                                          :target => Software::Target::TC_SERVER) %>
				    <% end %>
				  </li>
					
					<li>
				    <% if @budget.tc_software %>
				      <%= link_to t('msgs.thin_clients').humanize,
				                  budget_software_path(@budget, @budget.tc_software) %>
				    <% else %>
				      <%= link_to t('msgs.thin_clients').humanize,
				                  new_budget_software_path(@budget,
				                                          :target => Software::Target::TC) %>
				    <% end %>
				  </li>
				</ul>
			</small>
    </li>
		
		<li>
      <% if @budget.settings %>
        <%= link_to Settings.model_name.human.humanize,
                    budget_settings_path(@budget) %>
      <% else %>
        <%= link_to Settings.model_name.human.humanize,
                    new_budget_settings_path(@budget) %>
      <% end %>
    </li>
  </ul>
</p>

app/views/budgets/summarize.html.erb
<% content_for :head do %>
<style>
	th {
		text-align: left;
	}
</style>
<% end %>

<% content_for :page_title do %>
	<%= t('msgs.summary_of') %>  <%= h(@budget.name).humanize %>
<% end %>
<% content_for :sidenav, render(:partial => 'sidenav') %>

<table border="0" cellpadding="5" cellpadding="5" width="100%">
	<thead>
		<tr>
			<th><%= t('msgs.item') %></th>
			<th><%= t('msgs.desc') %></th>
			<th><%= t('msgs.unit_price') %></th>
			<th><%= t('msgs.qty') %></th>
			<th><%= t('msgs.subtotal') %></th>
		</tr>
	</thead>
	<tbody>
		<% to_table(@budget).each do |row| %>
		<tr>
			<% row.each do |col| %>
				<td><%= col %></td>
			<% end %>			
		</tr>
		<% end %>
	</tbody>
</table>

<br/>

<p>
	<%= Settings.human_attribute_name('total_cost').humanize %>:&nbsp;
	<strong>
		<%= number_to_currency @budget.settings.total_cost %>		
	</strong>
</p>